# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemoteMonitoringService(object):
    def setupUi(self, RemoteMonitoringService):
        RemoteMonitoringService.setObjectName("RemoteMonitoringService")
        RemoteMonitoringService.resize(1103, 659)
        self.centralwidget = QtWidgets.QWidget(RemoteMonitoringService)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.temp_graph = PlotWidget(self.centralwidget)
        self.temp_graph.setMinimumSize(QtCore.QSize(500, 300))
        self.temp_graph.setObjectName("temp_graph")
        self.gridLayout.addWidget(self.temp_graph, 0, 0, 1, 1)
        self.humidity_graph = PlotWidget(self.centralwidget)
        self.humidity_graph.setMinimumSize(QtCore.QSize(500, 300))
        self.humidity_graph.setObjectName("humidity_graph")
        self.gridLayout.addWidget(self.humidity_graph, 0, 1, 1, 1)
        self.temperature_btn = QtWidgets.QPushButton(self.centralwidget)
        self.temperature_btn.setMinimumSize(QtCore.QSize(200, 50))
        self.temperature_btn.setObjectName("temperature_btn")
        self.gridLayout.addWidget(self.temperature_btn, 1, 0, 1, 1)
        self.humidity_btn = QtWidgets.QPushButton(self.centralwidget)
        self.humidity_btn.setMinimumSize(QtCore.QSize(200, 50))
        self.humidity_btn.setFlat(False)
        self.humidity_btn.setObjectName("humidity_btn")
        self.gridLayout.addWidget(self.humidity_btn, 1, 1, 1, 1)
        self.alarm_btn = QtWidgets.QPushButton(self.centralwidget)
        self.alarm_btn.setMinimumSize(QtCore.QSize(500, 50))
        self.alarm_btn.setObjectName("alarm_btn")
        self.gridLayout.addWidget(self.alarm_btn, 2, 0, 1, 1)
        self.reset_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reset_btn.setMinimumSize(QtCore.QSize(500, 50))
        self.reset_btn.setObjectName("reset_btn")
        self.gridLayout.addWidget(self.reset_btn, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        RemoteMonitoringService.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RemoteMonitoringService)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1103, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        RemoteMonitoringService.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RemoteMonitoringService)
        self.statusbar.setObjectName("statusbar")
        RemoteMonitoringService.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(RemoteMonitoringService)
        self.actionNew.setObjectName("actionNew")
        self.actionClose = QtWidgets.QAction(RemoteMonitoringService)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(RemoteMonitoringService)
        QtCore.QMetaObject.connectSlotsByName(RemoteMonitoringService)

    def retranslateUi(self, RemoteMonitoringService):
        _translate = QtCore.QCoreApplication.translate
        RemoteMonitoringService.setWindowTitle(_translate("RemoteMonitoringService", "Remote Monitoring Service"))
        self.temperature_btn.setText(_translate("RemoteMonitoringService", "Temperature"))
        self.humidity_btn.setText(_translate("RemoteMonitoringService", "Humidity"))
        self.alarm_btn.setText(_translate("RemoteMonitoringService", "Fire an Alarm"))
        self.reset_btn.setText(_translate("RemoteMonitoringService", "Reset"))
        self.menuFile.setTitle(_translate("RemoteMonitoringService", "File"))
        self.actionNew.setText(_translate("RemoteMonitoringService", "New"))
        self.actionNew.setShortcut(_translate("RemoteMonitoringService", "Ctrl+N"))
        self.actionClose.setText(_translate("RemoteMonitoringService", "Close"))
        self.actionClose.setShortcut(_translate("RemoteMonitoringService", "Ctrl+Q"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RemoteMonitoringService = QtWidgets.QMainWindow()
    ui = Ui_RemoteMonitoringService()
    ui.setupUi(RemoteMonitoringService)
    RemoteMonitoringService.show()
    sys.exit(app.exec_())
